#!/usr/bin/env bash

PROJECT_NAME="OOD"
PROJECT_FULL="Open Offline Docs"

ROOT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE_DIR="${BASE_DIR:-$ROOT_PATH}"
SCRIPT_DIR="${SCRIPT_DIR:-$ROOT_PATH/scripts}"
MANAGER_DIR="$BASE_DIR/manager"
API_DIR="$BASE_DIR/api"
DOCKER_DIR="$BASE_DIR/docker"
DOCS_DIR="$BASE_DIR/docs"

PHP_PORT=8002
ASTRO_PORT=8003
PYTHON_PORT=8001
ALPINE_PORT=8004
FASTAPI_PORT=8000
SLIMPHP_PORT=8005
API_PORT=8080