site_name: Alpine.js Docs
site_description: A rugged, minimal framework for composing JavaScript behavior in your markup.
site_url: null
theme:
  name: material
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/lightbulb-auto
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: blue
    accent: cyan
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: blue
    accent: cyan
    toggle:
      icon: material/lightbulb-outline
      name: Switch to system preference
  features:
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  logo: https://alpinejs.dev/alpine_long.svg
  language: en

repo_name: alpinejs/alpine
repo_url: https://github.com/alpinejs/alpine

